# The environment variable TILED_SINGLE_USER_API_KEY must be set, as in:
#
#     TILED_SINGLE_USER_API_KEY=secret docker-compose up
#
# or using a environment file as described in the docker-compose documentation:
#
#     https://docs.docker.com/compose/environment-variables/set-environment-variables/
#
# Test using, for example:
#
#     python examples/write_and_read_back_data.py

version: "3.7"

services:
  tiled:
    image: ghcr.io/bluesky/databroker:v2.0.0b57
    volumes:
      - type: bind
        source: ./example_config
        target: /deploy/config
      - type: bind
        source: ./data
        target: /deploy/data
    environment:
      - TILED_SINGLE_USER_API_KEY=$TILED_SINGLE_USER_API_KEY
    ports:
      - 8000:8000
    networks:
      - backend
    depends_on:
      - mongo
  mongo:
    image: docker.io/mongo:6.0.4
    # These ports should not be exposed in production, but direct access
    # to the MongoDB may be useful for development and debugging.
    ports:
      - 27017:27017
    networks:
      - backend

networks:
  backend: {}
