package:
  name: metadatastore
  version: {{ environ['GIT_DESCRIBE_TAG'] }}.post{{ environ['GIT_DESCRIBE_NUMBER'] }}

source:
  git_url: ../

build:
  number: 0

  # Note that this will override the default build string with the Python
  # and NumPy versions
  string: {{ environ.get('GIT_BUILD_STR', '') }}_np{{ np }}py{{ py }}


requirements:
  build:
    - python
    - six

  run:
    - python
    - mongoengine
    - six
    - pyyaml

test:
  # Python imports
  imports:
    - metadataStore
    - metadataStore.commands
    - metadataStore.api
    - metadataStore.conf
    - metadataStore.odm_templates
    - metadataStore.document