# This is intended to be used with docker-compose.yml.
trees:
- path: /raw
  tree: databroker.mongo_normalized:MongoAdapter.from_uri
  args:
    uri: mongodb://mongo:27017/example_database
    handler_registry:
      NPY_SEQ: "handlers:NumpySeqHandler"
      SES_file_format: "handlers:SESHandler"
